# -*- coding: utf-8 -*-
"""cars_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlDIX10iPFrdHc8jQoJ1_FMip2Bn7SSj
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt


data=pd.read_json("https://storage.googleapis.com/tfjs-tutorials/carsData.json")

print(data)


X = data[['Weight_in_lbs','Cylinders']]
y = data['Acceleration']

model = linear_model.LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

MAE = mean_absolute_error(y, y_pred)
MSE = mean_squared_error(y, y_pred)

print("Ortalama Mutlak Hata (MAE): {:.4f}".format(MAE))
print("Ortalama Kare Hata (MSE): {:.4f}".format(MSE))