# -*- coding: utf-8 -*-
"""Kaba_Arama_Tekniği.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2wDt0qXX7gRa8dEtiNYTrS6BN58p5cv
"""

import numpy as np
import matplotlib.pyplot as plt

p = 0.0002
Min_r = 10e+6
Min_M = 10e+6
Adim = 0.01
r = np.arange(0, 10, Adim)
M = np.zeros_like(r)

for i in range(len(r)):
    h = 430 / (np.pi * r[i] ** 2)
    M[i] = p * (2 * np.pi * r[i] ** 2 + 2 * np.pi * r[i] * h)
    if M[i] < Min_M:
        Min_M = M[i]
        Min_r = r[i]

print('Maliyeti Minimum yapan r= {:.6f}'.format(Min_r))
print('Maliyeti Minimum yapan h= {:.6f}'.format(430 / (np.pi * (Min_r) ** 2)))


plt.figure(1)
plt.plot(r, M)
plt.xlabel('r')
plt.ylabel('M')
plt.grid(True)
plt.show()